#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# vim: set ts=4 sw=4 et

"""Create Ubuntu kernel packaging."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path
from typing import TYPE_CHECKING, NoReturn, Self
from urllib.request import urlretrieve

if TYPE_CHECKING:
    import io
    import types

import tomllib

KORG = "https://www.kernel.org/pub/linux/kernel"
UBUNTU_RELEASES = {
    "focal": "20.04",
    "jammy": "22.04",
    "noble": "24.04",
    "oracular": "24.10",
    "plucky": "25.04",
    "questing": "25.10",
    "resolute": "26.04",
}
DEB_SOURCE_FIELDS = [
    "Source",
    "Maintainer",
    "Uploaders",
    "Standards-Version",
    "Description",
    "Homepage",
    "Bugs",
    "Rules-Requires-Root",
    "Testsuite",
    "Testsuite-Triggers",
    "Vcs-Git",
    "Vcs-Browser",
    "Origin",
    "Section",
    "Priority",
    "Build-Depends",
    "Build-Depends-Arch",
    "Build-Depends-Indep",
    "Build-Conflicts",
    "Build-Conflicts-Arch",
    "Build-Conflicts-Indep",
]
DEB_BINARY_FIELDS = [
    "Package",
    "Package-Type",
    "Architecture",
    "Build-Profiles",
    "Protected",
    "Essential",
    "Build-Essential",
    "Multi-Arch",
    "Tag",
    "Description",
    "Homepage",
    "Section",
    "Priority",
    "Depends",
    "Pre-Depends",
    "Recommends",
    "Suggests",
    "Breaks",
    "Enhances",
    "Replaces",
    "Conflicts",
    "Provides",
    "Built-Using",
    "Static-Built-Using",
]


def merge(a: dict, b: dict) -> dict:
    """Merge dictionary b into dictionary a."""
    stack = []
    path = []
    b = iter(b.items())
    while True:
        try:
            (key, new) = next(b)
        except StopIteration:
            if not stack:
                return a
            a, b = stack.pop()
            path.pop()
            continue

        old = a.get(key)
        if isinstance(old, dict):
            path.append(key)
            if isinstance(new, dict):
                stack.append((a, b))
                a = old
                b = iter(new.items())
            else:
                raise TypeError(f"Overwriting table at {'.'.join(path)})")
        else:
            a[key] = new


class Spawn(subprocess.Popen):
    def __init__(
        self,
        *args: any,
        stdin=subprocess.DEVNULL,
        stdout=None,
        stderr=None,
        silent=False,
        **kwargs: any,
    ) -> Self:
        if isinstance(stdin, Path):
            stdin = stdin.open("rb")
        if isinstance(stdout, Path):
            stdout = stdout.open("wb")
        if isinstance(stderr, Path):
            stderr = stderr.open("wb")
        cmd = args[0]
        if not isinstance(cmd, list):
            cmd = list(args)
        if not silent:
            print(f"+ {' '.join(cmd)}")
        try:
            super().__init__(cmd, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs)
        finally:
            if hasattr(stdin, "close"):
                stdin.close()
            if hasattr(stdout, "close"):
                stdout.close()
            if hasattr(stderr, "close"):
                stderr.close()

    def _fail(self) -> NoReturn:
        raise subprocess.CalledProcessError(returncode=self.returncode, cmd=self.args)

    def check_returncode(self) -> None:
        self.wait()
        if self.returncode != 0:
            self._fail()

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        exc_traceback: types.TracebackType | None,
    ) -> bool:
        super().__exit__(exc_type, exc_value, exc_traceback)
        if self.returncode != 0 and (exc_type is None or exc_type is BrokenPipeError):
            self._fail()
        return False


class Config:
    CONTROL_TEMPLATE = re.compile(
        r"{{([^}]*)}}|(?P<tail>[ \t\n]+\Z)|(?P<empty>\n(?=\n))|(?P<newline>\n)",
        re.ASCII,
    )

    @staticmethod
    def _parse_config(config: Path) -> (str, dict):
        with config.open("rb") as cfile:
            firstline = cfile.readline().decode("utf-8")
            for line in cfile:
                if line == b"---\n":
                    break
            overrides = tomllib.load(cfile)
        return firstline, overrides

    @staticmethod
    def _parse_firstline(line: str) -> (str, str, str):
        match = re.match(r"([^ \t]*)[ \t]*\(([^\)]*)\)[ \t]*([^;]*)", line)
        if not match:
            raise ValueError(f"Unable to parse changelog entry: {line.rstrip()}")

        return match.group(1), match.group(2), match.group(3)

    @staticmethod
    def _validate_name(name: str) -> None:
        if not re.fullmatch(r"[a-z0-9+-.]*", name):
            raise ValueError(
                f"Invalid package name: {name}. "
                "Only a-z, 0-9, +, -, and . allowed in package names."
            )
        if not name.startswith("linux-"):
            raise ValueError(
                f'Invalid source package name: {name}. Must begin with "linux-".'
            )

    @staticmethod
    def _validate_version(version: str) -> (str, str, str, str):
        dash = version.rfind("-")
        if dash <= 0:
            raise ValueError(
                f"Invalid version: {version}. "
                "Must be of the form <upstream version>-<package revision>."
            )

        orig = version[:dash]
        rev = version[dash + 1 :]

        if not re.fullmatch(r"[0-9][A-Za-z0-9.+-:~]*", orig):
            raise ValueError(
                f"Invalid upstream version: {orig}. "
                "Only A-Z, a-z, 0-9, ., +, -, :, and ~ allowed."
            )
        match = re.fullmatch(r"([A-Za-z0-9]+)[.+~]*([A-Za-z0-9.+~]*)", rev)
        if not match:
            raise ValueError(
                f"Invalid revision: {rev}."
                "Only A-Z, a-z, 0-9, ., +, and ~ allowed in package revision."
            )

        abi = match.group(1)
        upload = match.group(2) or "0"
        return orig, rev, abi, upload

    @staticmethod
    def _validate_distro(distro: str) -> None:
        if " " in distro:
            raise ValueError("Only 1 distro supported.")
        if distro not in UBUNTU_RELEASES:
            raise ValueError(f"Unsupported Ubuntu release: {distro}.")

    def _massage_packages(self) -> None:
        pkgs = self.env["pkg"]
        source = pkgs["source"]
        build_depends = set()
        build_depends_arch = set()
        build_depends_indep = set()

        for name, pkg in pkgs.items():
            if name != "source":
                arch = pkg.get("Architecture", "any")
                if arch == "any":
                    arch = self.env["arch"]
                else:
                    arch = set(arch.split(" "))
                    if not arch <= self.arch:
                        continue
                    arch = " ".join(sorted(arch))
                pkg["Architecture"] = arch

            # Sort lists
            for field, value in pkg.items():
                if isinstance(value, list):
                    pkg[field] = sorted(set(value))

            if lst := pkg.get("Build-Depends"):
                build_depends.update(lst)
            if lst := pkg.get("Build-Depends-Arch"):
                build_depends_arch.update(lst)
            if lst := pkg.get("Build-Depends-Indep"):
                build_depends_indep.update(lst)

        if build_depends:
            source["Build-Depends"] = sorted(build_depends)
        if build_depends_arch:
            source["Build-Depends-Arch"] = sorted(build_depends_arch)
        if build_depends_indep:
            source["Build-Depends-Indep"] = sorted(build_depends_indep)

    def __init__(self, datadir: Path, config: Path) -> None:
        """Get value tree from given input config file."""
        firstline, overrides = self._parse_config(config)
        name, version, distro = self._parse_firstline(firstline)

        self._validate_name(name)
        orig, rev, abi, upload = self._validate_version(version)
        self._validate_distro(distro)

        with (datadir / distro / "defaults.toml").open("rb") as dfile:
            env = tomllib.load(dfile)

        merge(env, overrides)

        arch = env["arch"]
        if not isinstance(arch, list):
            arch = arch.split(" ")
        arch = set(arch)

        self.datadir = datadir
        self.path = config
        self.arch = arch
        self.env = env

        flavour = name[6:]
        env["pkg"]["source"]["Source"] = name
        env["version"] = version
        env.setdefault("orig", f"v{orig}")
        env["upstream-version"] = orig
        env["package-revision"] = rev
        env["abi-number"] = abi
        env["upload-number"] = upload
        env["kver"] = f"{orig.replace('~', '-')}-{abi}"
        env["krel"] = f"{env['kver']}-{flavour}"
        env["distro"] = distro
        env["flavour"] = flavour
        env["arch"] = " ".join(sorted(self.arch))

        with (datadir / "releases.toml").open("rb") as rfile:
            if data := tomllib.load(rfile).get(env["orig"]):
                env["orig-commit"] = data["commit"]
                env["orig-url"] = f"{KORG}/{data['path']}"
                env["orig-sha256"] = data["sha256"]

        self._massage_packages()

    def __getitem__(self, key: str) -> any:
        return self.env[key]

    def __contains__(self, key: str) -> bool:
        return key in self.env

    def arch_override(self, arch: str, key: str) -> None:
        arch = self.env[arch]
        if key in arch:
            return arch[key]
        return self.env.get(key)

    def _control_template(self, val: str) -> str:
        def replace(m: re.Match) -> str:
            if m.group("tail") is not None:
                return ""
            if m.group("empty") is not None:
                return "\n ."
            if m.group("newline") is not None:
                return "\n "
            g1 = m.group(1)
            if g1 == "KREL":
                return self.env["krel"]
            if g1 == "KVER":
                return self.env["kver"]
            if g1 == "FLAVOUR":
                return self.env["flavour"]
            return m.group(0)

        return self.CONTROL_TEMPLATE.sub(replace, val)

    def _write_prop(self, out: io.TextIOBase, key: str, val: list | str) -> None:
        if isinstance(val, list):
            if len(val) > 1:
                out.write(f"{key}:\n")
                for e in val:
                    out.write(f" {self._control_template(e)},\n")
            else:
                out.write(f"{key}: {self._control_template(val[0])}\n")
        else:
            out.write(f"{key}: {self._control_template(val)}\n")

    def _write_source(self, out: io.TextIOBase, pkg: dict) -> None:
        for key in DEB_SOURCE_FIELDS:
            if val := pkg.get(key):
                self._write_prop(out, key, val)
            # TODO: Handle XS-, XB-, and XC- fields
        out.write("\n")

    def _write_pkg(self, out: io.TextIOBase, pkg: dict) -> None:
        for key in DEB_BINARY_FIELDS:
            if val := pkg.get(key):
                self._write_prop(out, key, val)
            # TODO: Handle XS-, XB-, and XC- fields
        out.write("\n")

    def write_control(self, path: Path) -> None:
        pkgs = self.env["pkg"]
        with path.open("xt", encoding="utf-8") as cfile:
            self._write_source(cfile, pkgs["source"])
            self._write_pkg(cfile, pkgs["meta"])
            self._write_pkg(cfile, pkgs["meta-image"])
            self._write_pkg(cfile, pkgs["meta-headers"])
            self._write_pkg(cfile, pkgs["meta-tools"])
            self._write_pkg(cfile, pkgs["image"])
            self._write_pkg(cfile, pkgs["modules"])
            self._write_pkg(cfile, pkgs["headers"])
            self._write_pkg(cfile, pkgs["tools"])

    def write_changelog(self, path: Path) -> None:
        with self.path.open("rb") as src, path.open("xb") as dst:
            while True:
                line = src.readline()
                if line == b"---\n":
                    break
                dst.write(line)

    def write_config_mk(self, path: Path) -> None:
        per_arch_options = [
            "config",
            "tools",
            "cc",
            "vdso-install",
            "install-mod-strip",
            "force-compress-modules",
        ]
        with path.open("xt", encoding="utf-8") as dst:
            for arch in sorted(self.arch):
                for option in per_arch_options:
                    if value := self.arch_override(arch, option):
                        dst.write(f"{option}-{arch} := {value}\n")

            dst.write(f"flavour := {self.env['flavour']}\n")
            dst.write(f"krel := {self.env['krel']}\n")
            dst.write(f"abi-number := {self.env['abi-number']}\n")
            dst.write(f"upload-number := {self.env['upload-number']}\n")


def create_debian(config: Config, debian: Path) -> None:
    shutil.copytree(config.datadir / config["distro"] / "debian", debian)
    config.write_control(debian / "control")
    config.write_changelog(debian / "changelog")

    for arch in config.arch:
        kconfig = config.arch_override(arch, "config")
        if not kconfig:
            raise ValueError(f"No config specified for {arch}")

        if "/" in kconfig or (
            kconfig != "defconfig" and not kconfig.endswith("_defconfig")
        ):
            config_file = config.path.parent / kconfig
            if not config_file.is_file():
                raise ValueError(f"Could not find kernel config file: '{kconfig}'")

            if kconfig.endswith("_defconfig"):
                tgt = f"{arch}_defconfig"
            else:
                tgt = f"{arch}.config"

            shutil.copy(config_file, debian / tgt)
            config[arch]["config"] = False

    config.write_config_mk(debian / "config.mk")


def numeric_owner(info: tarfile.TarInfo) -> tarfile.TarInfo:
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def verify_orig_sha256(changes: Path, sha256: str) -> None:
    sh256line = re.compile(r" ([0-9a-f]{64}) [0-9]+ .*\.orig.tar.[gx]z\n")
    with changes.open("rt") as chf:
        for line in chf:
            if match := sh256line.fullmatch(line):
                found = match.group(1)
                if sha256 == found:
                    return
                raise ValueError(
                    "SHA256 of orig tarball did not match:\n"
                    f" expected {sha256}\n"
                    f" found    {found}"
                )
    raise ValueError("Could not find SHA256 of orig tarball in changes file.")


def create_source_pkg_quilt(
    config: Config,
    dest: Path,
    build: Path,
    repo: Path,
    orig: Path | None = None,
) -> None:
    source = config["pkg"]["source"]["Source"]
    debian = build / "debian"
    orig_tarball_xz = dest / f"{source}_{config['upstream-version']}.orig.tar.xz"
    orig_tarball_gz = dest / f"{source}_{config['upstream-version']}.orig.tar.gz"
    if orig:
        if orig.suffix == ".xz":
            orig_tarball = orig_tarball_xz
        elif orig.suffix == ".gz":
            orig_tarball = orig_tarball_gz
        if not orig_tarball.is_file():
            print(f"Creating {orig_tarball.name} symlink")
            orig_tarball.symlink_to(orig.relative_to(dest, walk_up=True))
    elif orig_tarball_xz.is_file():
        orig_tarball = orig_tarball_xz
    elif orig_tarball_gz.is_file():
        orig_tarball = orig_tarball_gz
    else:

        def reporthook(blocks: int, blocksize: int, totalsize: int) -> None:
            print(f"\r{100 * blocks * blocksize / totalsize:6.2f}%", end="")

        url = config["orig-url"]
        orig_tarball = orig_tarball_xz
        print(f"Downloading {url}")
        print("- use -o/--orig to use a previous download")
        try:
            urlretrieve(url, filename=orig_tarball, reporthook=reporthook)  # noqa: S310
        except:
            orig_tarball.unlink()
            raise
        finally:
            print()

    patches = debian / "patches"
    patches.mkdir(mode=0o755)
    patch_file = patches / f"{config['version']}.patch"
    print(f"Creating debian/patches/{patch_file.name}")
    Spawn(
        "git",
        "diff",
        "-U0",
        f"{config['orig-commit']}..{config['head']}",
        "--",
        ":(exclude)debian/",
        stdout=patch_file,
        cwd=repo,
    ).check_returncode()

    with (patches / "series").open("xt", encoding="utf-8") as out:
        out.write(f"{patch_file.name}\n")

    debian_tarball = dest / f"{source}_{config['version']}.debian.tar.xz"
    print(f"Creating {debian_tarball.name}")
    with (
        Spawn(
            "xz",
            "--verbose",
            "--compress",
            "--stdout",
            stdin=subprocess.PIPE,
            stdout=debian_tarball,
            cwd=dest,
        ) as xz,
        tarfile.open(mode="w|", fileobj=xz.stdin) as out,
    ):
        out.add(debian, "debian", recursive=True, filter=numeric_owner)

    print(f"Creating {source}_{config['version']}.dsc")
    Spawn(
        "dpkg-source",
        "--format=3.0 (custom)",
        "--target-format=3.0 (quilt)",
        "--build",
        source,
        orig_tarball.name,
        debian_tarball.name,
        cwd=dest,
    ).check_returncode()


def create_source_pkg_native(
    config: Config,
    dest: Path,
    build: Path,
    repo: Path,
) -> None:
    source = config["pkg"]["source"]["Source"]
    debian = build / "debian"

    tarball = f"{source}_{config['version']}.tar.xz"
    print(f"Creating {tarball}")
    with (
        Spawn(
            "git",
            "archive",
            "--format=tar",
            f"--prefix={source}/",
            config["head"],
            ":(exclude)debian/",
            stdout=subprocess.PIPE,
            cwd=repo,
        ) as git,
        Spawn(
            "xz",
            "--verbose",
            "--threads=0",
            "--compress",
            "--stdout",
            stdin=subprocess.PIPE,
            stdout=dest / tarball,
            cwd=dest,
        ) as xz,
        tarfile.open(mode="w|", fileobj=xz.stdin) as out,
    ):
        try:
            with tarfile.open(mode="r|", fileobj=git.stdout) as git_archive:
                while info := git_archive.next():
                    file = git_archive.extractfile(info) if info.isfile() else None
                    out.addfile(numeric_owner(info), fileobj=file)
        except tarfile.ReadError as e:
            if str(e) != "empty file":
                raise
        out.add(debian, f"{source}/debian", recursive=True, filter=numeric_owner)

    print(f"Creating {source}_{config['version']}.dsc")
    Spawn(
        "dpkg-source",
        "--format=3.0 (custom)",
        "--target-format=3.0 (native)",
        "--build",
        source,
        tarball,
        cwd=dest,
    ).check_returncode()


def create_source_pkg(
    config: Config,
    dest: Path,
    repo: Path,
    orig: Path | None = None,
    *,
    native: bool = False,
    include_orig: bool = True,
) -> None:
    source = config["pkg"]["source"]["Source"]
    build = dest / source
    build.mkdir(mode=0o755)

    buildinfo_file = f"{source}_{config['version']}_source.buildinfo"
    changes_file = dest / f"{source}_{config['version']}_source.changes"

    try:
        print("Creating debian directory")
        create_debian(config, build / "debian")

        if native:
            create_source_pkg_native(config, dest, build, repo)
        else:
            create_source_pkg_quilt(config, dest, build, repo, orig)

        print(f"Creating {buildinfo_file}")
        Spawn("dpkg-genbuildinfo", "--build=source", cwd=build).check_returncode()

        print(f"Creating {changes_file.name}")
        Spawn(
            "dpkg-genchanges",
            "--build=source",
            "-sa" if include_orig else "-sd",
            f"-O../{changes_file.name}",
            cwd=build,
        ).check_returncode()
    finally:
        shutil.rmtree(build)

    if not native:
        try:
            verify_orig_sha256(changes_file, config["orig-sha256"])
        except:
            changes_file.unlink()
            raise

    print("Source package built successfully \\o/")
    print(f"Sign package:    debsign {changes_file}")
    print(f"Upload package:  dput <PPA> {changes_file}")


def parse_args() -> argparse.Namespace:
    def file(path: str) -> Path:
        path = Path(path)
        if not path.is_file():
            raise ValueError
        return path

    def directory(path: str) -> Path:
        path = Path(path)
        if not path.is_dir():
            raise ValueError
        return path

    def mkdir(path: str) -> Path:
        path = Path(path)
        if path.is_dir():
            return path
        if path.exists() or not path.parent.is_dir():
            raise ValueError
        path.mkdir(mode=0o755)
        return path

    here = Path()

    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Create Ubuntu kernel packaging",
    )
    parser.add_argument(
        "config",
        type=file,
        help="Debian changelog with configuration in TOML footer",
    )
    parser.add_argument(
        "--datadir",
        type=Path,
        default=Path(__file__).parent.resolve() / "ubuntu",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "-o",
        "--orig",
        type=file,
        help="path to orig tarball",
    )
    parser.add_argument(
        "-t",
        "--tree",
        type=directory,
        default=here,
        help="path to Linux kernel git tree",
    )
    parser.add_argument(
        "-d",
        "--dest",
        type=mkdir,
        default=here,
        help="output directory",
    )
    parser.add_argument(
        "--include-orig",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="include orig tarball in upload",
    )
    parser.add_argument(
        "-N",
        "--native",
        action="store_true",
        help='create "native" debian package without an orig tarball',
    )
    parser.add_argument(
        "-D",
        "--debian",
        action="store_true",
        help="just create the debian directory",
    )
    return parser.parse_args()


def run() -> int:
    def eprint(*args: any, **kwargs: any) -> int:
        print(*args, file=sys.stderr, **kwargs)
        return 1

    args = parse_args()
    try:
        config = Config(args.datadir, args.config)
    except ValueError as e:
        return eprint(str(e))
    except FileNotFoundError as e:
        return eprint(f"{e.strerror}: '{e.filename}'")

    if not args.native and not args.debian:
        if "orig-commit" not in config:
            return eprint(
                f"Don't know version {config['orig']}.\n"
                "If this is a pre-release (-rc) kernel please use -N."
            )
        if (
            Spawn(
                "git",
                "merge-base",
                "--is-ancestor",
                config["orig-commit"],
                config["head"],
                cwd=args.tree,
                silent=True,
            ).wait()
            != 0
        ):
            return eprint(
                f"{config['orig']} aka {config['orig-commit']} "
                f"is not an ancestor of {config['head']}.\n"
                f"Are you sure this kernel is based on {config['orig']}?"
            )

    try:
        if args.debian:
            debian = args.dest / "debian"
            print(f"Creating {debian}")
            create_debian(config, debian)
        else:
            create_source_pkg(
                config,
                args.dest,
                args.tree,
                args.orig,
                native=args.native,
                include_orig=args.include_orig,
            )
    except ValueError as e:
        return eprint(str(e))
    except FileExistsError as e:
        return eprint(f"Error creating '{e.filename}': {e.strerror}")
    except FileNotFoundError as e:
        return eprint(f"Error opening '{e.filename}': {e.strerror}")
    except KeyboardInterrupt:
        return eprint("interrupted")
    except subprocess.CalledProcessError as e:
        return e.returncode

    return 0


if __name__ == "__main__":
    sys.exit(run())
